version: 2.1

shed_cache_key: &shed_cache_key go-sc-tools-20210508-{{ checksum "shed.lock" }}

jobs:
  test:
    docker:
      - image: cszatmary/cimg-go:1.16
    steps:
      - checkout
      - restore_cache:
          name: Restore tool dependency cache
          keys:
            - *shed_cache_key
      - run:
          name: Install dependencies
          command: make setup
      - save_cache:
          name: Cache tool dependencies
          key: *shed_cache_key
          paths:
            - ~/.cache/shed
      - run:
          name: Check files are formatted
          command: make check-fmt
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Run tests
          command: make test

workflows:
  test:
    jobs:
      - test
